AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LatestAmiID:
    Description: Latest free tier grade amazon machine image.
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    AllowedValues:
      - '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  InstanceType:
    Description: Type of the machine which will be used for this instance.
    AllowedValues:
      - t2.nano
      - t2.micro
    Default: t2.micro
    Type: String

  KeyName:
    Description: Key pair for accessing the machine.
    Default: ssh_key_default
    Type: 'AWS::EC2::KeyPair::KeyName'

  AvaliabilityZones:
    Description: List of avaliability zones for creating instances in.
    Default: us-west-2a,us-west-2b
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'

  VPC:
    Description: VPC id.
    Default: vpc-4c7a5c34
    Type: 'AWS::EC2::VPC::Id'

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group with tcp + ssh access.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  EC2LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: 'ec2-launch-template'
      LaunchTemplateData:
        ImageId: !Ref LatestAmiID
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        UserData:
          Fn::Base64:
            !Sub |
            #!/bin/bash
            yum -y install java-1.8.0-openjdk
            java -version > ./java-output.txt
  AutoscalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones: !Ref AvaliabilityZones
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'